### ISSUE TITLE
Merge into pion/datachannel?

### ISSUE THREAD

**Issue by stv0g** [pions/dcnet#2]
Once this repo reached some level of maturity, we might consider integrating it into pion/datachannel

**Comment by Sean-Der** [comment]
@stv0g Either that or we deprecate this repo. I am leaning towards deprecation for the following reasons.

**Doesn't seem to be used**

This package doesn't appear on pkg.go.dev so no one has ever used it since Go Modules has been released (I believe?). Searching on github.com/search doesn't turn up any users either.


**Encourage portability**

I prefer the w3c APIs for WebRTC users. This allows users to easily switch between Go/Python/Rust etc... if we create a lot of Pion specific APIs they are stuck on Go.

**Comment by stv0g** [comment]
Thanks for the feedback @Sean-Der. 

Lets archive the repo then :)
